New post: On-chain Font
fiveoutofnine/www pull request #35
Opened 2024-06-08 02:28 UTC by fiveoutofnine

2024-06-10 23:59 UTC, shunkakinoki requested changes

2024-06-10 23:59 UTC, shunkakinoki commented on app/blog/(components)/header/index.tsx
> +      <div className="-mt-3 flex h-5 items-center text-base leading-5 text-gray-11 md:-mt-2.5">
md:-mt-1.5

2024-06-11 00:04 UTC, fiveoutofnine commented on app/blog/(components)/header/index.tsx
> +      <div className="-mt-3 flex h-5 items-center text-base leading-5 text-gray-11 md:-mt-2.5">
no

2024-06-11 00:04 UTC, fiveoutofnine commented on app/blog/(components)/header/index.tsx
> +      <div className="-mt-3 flex h-5 items-center text-base leading-5 text-gray-11 md:-mt-2.5">
too much

2024-06-11 00:08 UTC, merged